on:
  workflow_call:
    inputs:
      infra_folder_path:
        required: false
        type: string
      codeartifact_encrypted_token_dev:
        required: false
        type: string
      codeartifact_encrypted_token_prod:
        required: false
        type: string
    secrets:
      GPG_CODEARTIFACT_TOKEN_PASSPHRASE:
        required: false
    outputs:
      ecr-image:
        description: "The application's image" 
        value: ${{ jobs.build-and-push.outputs.ecr-image }}
      env-id:
        description: "The Environment Identifier" 
        value: ${{ jobs.build-and-push.outputs.env-id }}
      env-suffix:
        description: "The Environment Identifier" 
        value: ${{ jobs.build-and-push.outputs.env-suffix }}
      init-deployment:
        description: "The flag defining is it's an initial deployment or not" 
        value: ${{ jobs.build-and-push.outputs.init-deployment }}

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  set-environment-variables:
    runs-on: ubuntu-latest
    outputs:
      infra_folder_path: ${{ steps.infra-folder-path.outputs.infra_folder_path }}
    steps:
      - name: Check infra folder path
        id: infra-folder-path
        run: |
          FOLDER_PATH=${{ inputs.infra_folder_path }}
          if [[ -z $FOLDER_PATH ]]; then
            FOLDER_PATH=infra/
          else
            FOLDER_PATH=${{ inputs.infra_folder_path }}/
          fi
          echo "infra_folder_path=$FOLDER_PATH" >> "$GITHUB_OUTPUT"

  build-and-push:
    needs:
      - set-environment-variables
    runs-on: ubuntu-latest
    outputs:
      ecr-image: ${{ steps.ecr-image-out.outputs.ECR_IMAGE }}
      env-id: ${{ steps.set-environment.outputs.ENVIRONMENT_ID }}
      env-suffix: ${{ steps.set-environment.outputs.ENVIRONMENT_SUFFIX }}
      init-deployment: ${{ steps.check-init-deploy.outputs.INITIAL_DEPLOYMENT }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:master
      - name: Set deployment env
        id: set-environment
        run: |
          if [ ${{ github.event_name }} == 'pull_request' ]; then
            echo "This is a review environment"
            cat ${{ needs.set-environment-variables.outputs.infra_folder_path }}environments/review.env >> "$GITHUB_ENV"
            echo "ENVIRONMENT_ID=review" >> "$GITHUB_OUTPUT"
            echo "ENVIRONMENT_SUFFIX=${{ github.event.pull_request.number }}" >> "$GITHUB_OUTPUT"
          else
            echo "This is a production environment"
            cat ${{ needs.set-environment-variables.outputs.infra_folder_path }}environments/production.env >> "$GITHUB_ENV"
            echo "ENVIRONMENT_ID=production" >> "$GITHUB_OUTPUT"
            echo "ENVIRONMENT_SUFFIX=" >> "$GITHUB_OUTPUT"
          fi
      
      - name: Configure AWS Credentials
        id: configure-aws-creds
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: ${{ env.AWS_CD_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
          mask-aws-account-id: false
      
      - name: Check and Create ECR Repository with Lifecycle Policy
        run: |
          # Extract repository name from ECR_REGISTRY (remove the AWS account and region prefix)
          REPOSITORY_NAME=$(echo "${{ env.ECR_REGISTRY }}" | awk -F'/' '{print $2}')
          echo "Checking if ECR repository $REPOSITORY_NAME exists..."
          
          # Check if repository exists
          if ! aws ecr describe-repositories --repository-names "$REPOSITORY_NAME" 2>/dev/null; then
            echo "ECR repository $REPOSITORY_NAME does not exist. Creating it..."
            aws ecr create-repository --repository-name "$REPOSITORY_NAME"
            echo "ECR repository created successfully."
          else
            echo "ECR repository $REPOSITORY_NAME already exists."
          fi
          
          # Check if the lifecycle policy already exists
          echo "Checking if lifecycle policy already exists..."
          EXISTING_POLICY=$(aws ecr get-lifecycle-policy --repository-name "$REPOSITORY_NAME" --output json 2>/dev/null || echo "")
          
          if [ -z "$EXISTING_POLICY" ]; then
            echo "No existing lifecycle policy found. Creating new policy..."
            # Set environment-specific lifecycle policy
            LIFECYCLE_POLICY='{
              "rules": [
                {
                  "rulePriority": 1,
                  "description": "Keep 50 latest untagged images for caching",
                  "selection": {
                    "tagStatus": "untagged",
                    "countType": "imageCountMoreThan",
                    "countNumber": 50
                  },
                  "action": {
                    "type": "expire"
                  }
                },
                {
                  "rulePriority": 2,
                  "description": "Keep all production, dev, stable and latest images",
                  "selection": {
                    "tagStatus": "tagged",
                    "tagPrefixList": ["production-", "dev", "stable", "latest"],
                    "countType": "imageCountMoreThan",
                    "countNumber": 999999
                  },
                  "action": {
                    "type": "expire"
                  }
                },
                {
                  "rulePriority": 3,
                  "description": "Keep 10 latest review images",
                  "selection": {
                    "tagStatus": "tagged",
                    "tagPrefixList": ["review-"],
                    "countType": "imageCountMoreThan",
                    "countNumber": 10
                  },
                  "action": {
                    "type": "expire"
                  }
                },
                {
                  "rulePriority": 4,
                  "description": "Keep 10 latest integration images",
                  "selection": {
                    "tagStatus": "tagged",
                    "tagPrefixList": ["integration-"],
                    "countType": "imageCountMoreThan",
                    "countNumber": 10
                  },
                  "action": {
                    "type": "expire"
                  }
                }
              ]
            }'
            
            aws ecr put-lifecycle-policy --repository-name "$REPOSITORY_NAME" --lifecycle-policy-text "$LIFECYCLE_POLICY"
            echo "Lifecycle policy set successfully."
          else
            echo "Lifecycle policy already exists. Skipping policy creation."
          fi
      
      - name: Clean up old images
        run: |
          # Extract repository name from ECR_REGISTRY (remove the AWS account and region prefix)
          REPOSITORY_NAME=$(echo "${{ env.ECR_REGISTRY }}" | awk -F'/' '{print $2}')
          echo "Cleaning up images in repository: $REPOSITORY_NAME"
          
          # Get all image details including tags
          echo "Fetching all images from repository..."
          IMAGES=$(aws ecr list-images --repository-name "$REPOSITORY_NAME" --output json)
          
          # Define valid patterns
          VALID_PATTERNS=("production-" "dev" "latest" "review-" "integration-" "stable")
          
          # Process each image
          echo "Processing images..."
          echo "$IMAGES" | jq -r '.imageDetails[] | select(.imageTags != null) | .imageTags[]' | while read -r tag; do
            echo "Checking tag: $tag"
            
            # Skip if tag is empty
            [ -z "$tag" ] && continue
            
            # Check if tag matches any valid pattern
            is_valid=false
            for pattern in "${VALID_PATTERNS[@]}"; do
              if [[ "$tag" == *"$pattern"* ]]; then
                is_valid=true
                echo "Tag '$tag' matches pattern '$pattern'"
                break
              fi
            done
            
            # If tag doesn't match any pattern, delete it
            if [ "$is_valid" = false ]; then
              echo "Deleting image with tag: $tag"
              aws ecr batch-delete-image --repository-name "$REPOSITORY_NAME" --image-ids "imageTag=$tag"
            fi
          done
          echo "Cleanup completed"
      
      - name: Check if it's initial deployment
        id: check-init-deploy
        run: |
          if [ ${{ github.event_name }} == 'pull_request' ]; then
            echo "Checking if it's an initial deployment for ${{ env.ProductName }}-${{ github.event.pull_request.number }} stack"
            if aws cloudformation describe-stacks --stack-name ${{ env.ProductName }}-${{ github.event.pull_request.number }}; then
              echo "Deployment exists"
              echo "INITIAL_DEPLOYMENT=false" >> "$GITHUB_OUTPUT"
            else
              echo "This is an initial deployment"
              echo "INITIAL_DEPLOYMENT=true" >> "$GITHUB_OUTPUT"
            fi
          else
            echo "Checking if it's an initial deployment for ${{ env.ProductName }} stack"
            if aws cloudformation describe-stacks --stack-name ${{ env.ProductName }}; then
              echo "Deployment exists"
              echo "INITIAL_DEPLOYMENT=false" >> "$GITHUB_OUTPUT"
            else
              echo "This is an initial deployment"
              echo "INITIAL_DEPLOYMENT=true" >> "$GITHUB_OUTPUT"
            fi
          fi
      
      - name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: "${{ env.ECR_REGISTRY }}"

      - name: Decrypt Codeartifact dev token
        if: "${{ inputs.codeartifact_encrypted_token_dev != '' }}"
        run: |
          token=$(gpg --decrypt --quiet --batch --passphrase "${{ secrets.GPG_CODEARTIFACT_TOKEN_PASSPHRASE }}" --output - <(echo "${{ inputs.codeartifact_encrypted_token_dev }}" | base64 --decode))
          echo "::add-mask::$token"
          echo "CODEARTIFACT_TOKEN_DEV=$token" >> "$GITHUB_ENV"

      - name: Decrypt Codeartifact prod token
        if: "${{ inputs.codeartifact_encrypted_token_prod != '' }}"
        run: |
          token=$(gpg --decrypt --quiet --batch --passphrase "${{ secrets.GPG_CODEARTIFACT_TOKEN_PASSPHRASE }}" --output - <(echo "${{ inputs.codeartifact_encrypted_token_prod }}" | base64 --decode))
          echo "::add-mask::$token"
          echo "CODEARTIFACT_TOKEN_PROD=$token" >> "$GITHUB_ENV"
      
      - name: Build And Push Docker Image
        uses: docker/build-push-action@v5
        if: ${{ (github.event_name != 'pull_request') }}
        with:
          push: true
          tags: ${{ env.ECR_REGISTRY }}:production-${{ github.sha }}
          cache-from: ${{ env.ECR_REGISTRY }}:stable
          cache-to: type=registry,ref=${{ env.ECR_REGISTRY }}:stable,mode=max,image-manifest=true,oci-mediatypes=true
          target: production
          secrets: |
            CODEARTIFACT_TOKEN_DEV=${{ env.CODEARTIFACT_TOKEN_DEV }}
            CODEARTIFACT_TOKEN_PROD=${{ env.CODEARTIFACT_TOKEN_PROD }}
          
      - name: Build And Push Docker Image PR
        uses: docker/build-push-action@v5
        if: ${{ (github.event_name == 'pull_request') }}
        with:
          push: true
          tags: ${{ env.ECR_REGISTRY }}:review-${{ github.sha }}
          cache-from: ${{ env.ECR_REGISTRY }}:latest
          cache-to: type=registry,ref=${{ env.ECR_REGISTRY }}:latest,mode=max,image-manifest=true,oci-mediatypes=true
          target: production
          secrets: |
            CODEARTIFACT_TOKEN_DEV=${{ env.CODEARTIFACT_TOKEN_DEV }}
            CODEARTIFACT_TOKEN_PROD=${{ env.CODEARTIFACT_TOKEN_PROD }}
      
      - name: Output ECR image
        id: ecr-image-out
        shell: bash
        run: |
          if [ ${{ github.event_name }} == 'pull_request' ]; then
            ECR_IMAGE=${{ env.ECR_REGISTRY }}:review-${{ github.sha }}
          else
            ECR_IMAGE=${{ env.ECR_REGISTRY }}:production-${{ github.sha }}
          fi
          echo "ECR_IMAGE=$ECR_IMAGE" >> "$GITHUB_OUTPUT"
          echo "The ECR image arn is $ECR_IMAGE"
