on:
  workflow_call:
    secrets:
      RELEASE_TOKEN:
        required: true
    outputs:
      latest-release-version:
        description: "The last version"
        value: ${{ jobs.bump.outputs.latest-release-version }}
      

jobs:
  bump:
    runs-on: ubuntu-latest
    outputs:
      latest-release-version: ${{ steps.release.outputs.VERSION }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Install dependencies
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      
      - name: Install dependencies
        run: yarn install
      
      - name: Release
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: npx semantic-release
