name: Dependabot approve and set auto merge
on:
  workflow_call:
    inputs:
      pr_url:
        description: The PR url. It can be provided by the github.event.pull_request.html_url
        required: true
        type: string
      merge_strategy:
        description: The strategy to use for merge. Currently merge and rebase are supported
        required: false
        default: rebase
        type: string
  
permissions:
  contents: write
  pull-requests: write
  
jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Approve Dependabot PRs
        run: gh pr review --approve "${{ inputs.pr_url }}"
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --"${{ inputs.merge_strategy }}" "${{ inputs.pr_url }}"
        env:
          GH_TOKEN: ${{ github.token }}
