on:
  workflow_call:
    inputs:
      python_version:
        required: false
        default: '3.10'
        type: string

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  precommit:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python ${{ inputs.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}
          architecture: x64

      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - name: Run pre-commit
        run: make pre-commit
