on:
  workflow_call:
    inputs:
      BUILDX_LOCAL_CACHE_DIR:
        required: false
        type: string
      codeartifact_encrypted_token_dev:
        required: false
        type: string
      codeartifact_encrypted_token_prod:
        required: false
        type: string
    secrets:
      GPG_CODEARTIFACT_TOKEN_PASSPHRASE:
        required: false

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  precommit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Build image
        if: "${{ inputs.BUILDX_LOCAL_CACHE_DIR == '' }}"
        uses: Orfium/orfium-github-actions/.github/actions/docker-build@feat/BEC-446_v2_reusable_workflows
        with:
          BUILDX_LOCAL_CACHE_DIR: ${{ inputs.BUILDX_LOCAL_CACHE_DIR }}
          codeartifact_encrypted_token_dev: ${{ inputs.codeartifact_encrypted_token_dev }}
          codeartifact_encrypted_token_prod: ${{ inputs.codeartifact_encrypted_token_prod }}
      
      - name: Run pre commit
        run: make pre-commit args="--all-files"
      
      - name: Tear down the Stack
        run: make down-volumes
