on:
  workflow_call:
    inputs:
      BUILDX_LOCAL_CACHE_DIR:
        required: false
        type: string

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  precommit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Set up Local Cache for Docker layers
        if: "${{ inputs.BUILDX_LOCAL_CACHE_DIR != '' }}"
        uses: actions/cache@v3
        with:
          path: ${{ inputs.BUILDX_LOCAL_CACHE_DIR }}
          key: ${{ runner.os }}-buildx-local-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-local-

      - name: Build local image from Cache
        if: "${{ inputs.BUILDX_LOCAL_CACHE_DIR != '' }}"
        uses: docker/build-push-action@v3
        with:
          push: false
          load: true
          target: local
          tags: ${{ github.event.repository.name }}
          cache-from: type=local,src=${{ inputs.BUILDX_LOCAL_CACHE_DIR }}
      
      - name: Build local image
        if: "${{ inputs.BUILDX_LOCAL_CACHE_DIR == '' }}"
        uses: docker/build-push-action@v3
        with:
          push: false
          load: true
          target: local
          tags: ${{ github.event.repository.name }}
      
      - name: Run pre commit PR
        if: ${{ (github.event_name == 'pull_request') }}
        run: |
          # shellcheck disable=SC2129
          make pre-commit args="--from-ref ${{ github.event.pull_request.base.sha }} --to-ref ${{ github.event.pull_request.head.sha }}"
        
      - name: Run pre commit branch
        if: ${{ (github.event_name != 'pull_request') }}
        run: make pre-commit args="--all-files"
      
      - name: Tear down the Stack
        run: make down-volumes
