on:
  workflow_call:
    inputs:
      COVERAGE_CACHE_DIR:
        required: true
        type: string
      RUNNER:
        required: false
        type: string
        default: ubuntu-latest
    secrets:
      SONAR_TOKEN:
        required: true
      SONAR_HOST_URL:
        required: true

jobs:
  sonarqube:
    runs-on: ${{ inputs.RUNNER }}
    steps:
      - name: Declare Coverage Cache Registry
        id: coverage-cache
        uses: actions/cache@v4
        with:
          path: ${{ inputs.COVERAGE_CACHE_DIR }}
          key: ${{ runner.os }}-coverage-reports-${{ github.sha }}

      - name: Check Out Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Retrieve Cached Coverage
        run: mv ${{ inputs.COVERAGE_CACHE_DIR }}/coverage.xml ./coverage.xml

      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -X

      - uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
