on:
  workflow_call:
    inputs:
      BUILDX_LOCAL_CACHE_DIR:
        required: false
        type: string
      RUN_UI_TESTS:
        required: false
        type: boolean
        default: false
      RUN_API_TESTS:
        required: false
        type: boolean
        default: false
      PUBLISH_TESTRAIL_RESULTS:
        required: false
        type: boolean
        default: false
      codeartifact_encrypted_token_dev:
        required: false
        type: string
      codeartifact_encrypted_token_prod:
        required: false
        type: string
    secrets:
      TESTRAIL_PASSWORD:
        description: Password for Orfium's TestRail account
        required: false
      GPG_CODEARTIFACT_TOKEN_PASSPHRASE:
        required: false

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
  TESTRAIL_USERNAME: "qa@orfium.com"

jobs:
  end-to-end-api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Local Cache for Docker layers
        if: "${{ inputs.BUILDX_LOCAL_CACHE_DIR != '' }}"
        uses: actions/cache@v3
        with:
          path: ${{ inputs.BUILDX_LOCAL_CACHE_DIR }}
          key: ${{ runner.os }}-buildx-local-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-local-

      - name: Decrypt Codeartifact dev token
        if: "${{ inputs.codeartifact_encrypted_token_dev != '' }}"
        run: |
          token=$(gpg --decrypt --quiet --batch --passphrase "${{ secrets.GPG_CODEARTIFACT_TOKEN_PASSPHRASE }}" --output - <(echo "${{ inputs.codeartifact_encrypted_token_dev }}" | base64 --decode))
          echo "::add-mask::$token"
          echo "CODEARTIFACT_TOKEN_DEV=$token" >> "$GITHUB_ENV"

      - name: Decrypt Codeartifact prod token
        if: "${{ inputs.codeartifact_encrypted_token_prod != '' }}"
        run: |
          token=$(gpg --decrypt --quiet --batch --passphrase "${{ secrets.GPG_CODEARTIFACT_TOKEN_PASSPHRASE }}" --output - <(echo "${{ inputs.codeartifact_encrypted_token_prod }}" | base64 --decode))
          echo "::add-mask::$token"
          echo "CODEARTIFACT_TOKEN_PROD=$token" >> "$GITHUB_ENV"

      - name: Build local image from Cache
        if: "${{ inputs.BUILDX_LOCAL_CACHE_DIR != '' }}"
        uses: docker/build-push-action@v3
        with:
          push: false
          load: true
          target: local
          tags: ${{ github.event.repository.name }}
          cache-from: type=local,src=${{ inputs.BUILDX_LOCAL_CACHE_DIR }}
          secrets: |
            CODEARTIFACT_TOKEN_DEV=${{ env.CODEARTIFACT_TOKEN_DEV }}
            CODEARTIFACT_TOKEN_PROD=${{ env.CODEARTIFACT_TOKEN_PROD }}

      - name: Build local image
        if: "${{ inputs.BUILDX_LOCAL_CACHE_DIR == '' }}"
        uses: docker/build-push-action@v3
        with:
          push: false
          load: true
          target: local
          tags: ${{ github.event.repository.name }}
          secrets: |
            CODEARTIFACT_TOKEN_DEV=${{ env.CODEARTIFACT_TOKEN_DEV }}
            CODEARTIFACT_TOKEN_PROD=${{ env.CODEARTIFACT_TOKEN_PROD }}

      - name: Run End to End API tests
        if: ${{ inputs.RUN_API_TESTS }}
        run: make e2e-api-tests

      - name: Run End to End UI tests
        if: ${{ inputs.RUN_UI_TESTS }}
        run: make e2e-ui-tests

      - name: Publish test results to TestRail
        if: always() && inputs.PUBLISH_TESTRAIL_RESULTS
        env:
          TESTRAIL_PASSWORD: ${{ secrets.TESTRAIL_PASSWORD }}
        run: make testrail-results

      - name: Tear down the Stack
        run: make down-volumes

