on:
  workflow_call:
    inputs:
      BUILDX_LOCAL_CACHE_DIR:
        required: false
        type: string
      RUN_UI_TESTS:
        required: false
        type: boolean
        default: false
      RUN_API_TESTS:
        required: false
        type: boolean
        default: false
      PUBLISH_TESTRAIL_RESULTS:
        required: false
        type: boolean
        default: false
    secrets:
      TESTRAIL_PASSWORD:
        description: Password for Orfium's TestRail account
        required: false

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
  TESTRAIL_USERNAME: "qa@orfium.com"
  TESTRAIL_PASSWORD: ${{ secrets.TESTRAIL_PASSWORD }}

jobs:
  end-to-end-api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Local Cache for Docker layers
        if: "${{ inputs.BUILDX_LOCAL_CACHE_DIR != '' }}"
        uses: actions/cache@v3
        with:
          path: ${{ inputs.BUILDX_LOCAL_CACHE_DIR }}
          key: ${{ runner.os }}-buildx-local-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-local-

      - name: Build local image from Cache
        if: "${{ inputs.BUILDX_LOCAL_CACHE_DIR != '' }}"
        uses: docker/build-push-action@v3
        with:
          push: false
          load: true
          target: local
          tags: ${{ github.event.repository.name }}
          cache-from: type=local,src=${{ inputs.BUILDX_LOCAL_CACHE_DIR }}

      - name: Build local image
        if: "${{ inputs.BUILDX_LOCAL_CACHE_DIR == '' }}"
        uses: docker/build-push-action@v3
        with:
          push: false
          load: true
          target: local
          tags: ${{ github.event.repository.name }}

      - name: Run End to End API tests
        if: ${{ inputs.RUN_API_TESTS }}
        run: make e2e-api-tests

      - name: Run End to End UI tests
        if: ${{ inputs.RUN_UI_TESTS }}
        run: make e2e-ui-tests

      - name: Publish test results to TestRail
        if: always() && inputs.PUBLISH_TESTRAIL_RESULTS
        run: make testrail-results

      - name: Tear down the Stack
        run: make down-volumes

